docs: add ACES and 360 projection management documentation
Also fixes:
- GPU shader: Replace Unicode arrows causing MSVC error C2220
- AMCP: Fix MIXER COLORSPACE query response to be human-readable
- AMCP: Fix MIXER COLORSPACE registration to allow 0 parameters (query mode)